version: '3'
networks:
  bridge:
services:
  nginx:
    container_name: daily-nginx
    image: nginx:latest
    hostname: daily-nginx
    restart: always
    networks:
      - bridge
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  mongo1:
    container_name: daily-mongo-1
    image: mongo:latest
    hostname: daily-mongo1
    networks:
      - bridge
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data1:/data/db
    restart: always
    entrypoint: mongod --replSet mongo-set --bind_ip daily-mongo1 --port 27017

  mongo2:
    container_name: daily-mongo-2
    image: mongo:latest
    hostname: daily-mongo2
    networks:
      - bridge
    ports:
      - "27018:27017"
    volumes:
      - ./mongo/data2:/data/db
    restart: always
    entrypoint: mongod --replSet mongo-set --bind_ip daily-mongo2 --port 27017

  mongo3:
    container_name: daily-mongo-3
    image: mongo:latest
    hostname: daily-mongo3
    networks:
      - bridge
    ports:
      - "27019:27017"
    volumes:
      - ./mongo/data3:/data/db
    restart: always
    entrypoint: mongod --replSet mongo-set --bind_ip daily-mongo3 --port 27017

  app:
    container_name: daily-service
    restart: always
    networks:
      - bridge
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - /home/maysham/.m2:/root/.m2
    expose:
      - "8081"
    depends_on:
      - nginx
      - mongo1
      - mongo2
      - mongo3
    command:
      - /bin/sh
      - -c
      - |
        mvn clean package
        java -jar /app/target/daily-0.0.1-SNAPSHOT.jar --spring.profiles.active=docker