version: '3'
services:
  nginx:
   container_name: daily-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d

  mysql:
   container_name: daily-mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: daily
    MYSQL_ROOT_PASSWORD: admin
    MYSQL_ROOT_HOST: '%'
   ports:
   - "3306:3306"
   restart: always

  app:
    restart: always
    build: .
    working_dir: .
    volumes:
      - .:.
      - ~/.m2:/root/.m2
    expose:
      - "8081"
    depends_on:
      - nginx
      - mysql
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker