version: '3'
services:
  nginx:
    container_name: daily-nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  hbase:
    container_name: daily-hbase
    image: maysham/hbase:latest
    hostname: "daily-hbase"
    ports:
      - "2181:2181"
      - "16010:16010"
      - "16000:16000"
      - "16020:16020"
    restart: always

  elasticsearch:
    container_name: daily-es
    image: elasticsearch:6.5.3
    environment:
      discovery.type: "single-node"
    network_mode: host
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always

  elasticsearch-head:
    container_name: daily-es-head
    image: alivv/elasticsearch-head:latest
    ports:
      - "9100:9100"
    restart: always

  mongo:
    container_name: daily-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always

  app:
    container_name: daily-service
    restart: always
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    expose:
      - "8081"
    depends_on:
      - nginx
      - hbase
      - elasticsearch
      - elasticsearch-head
      - mongo
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker