version: '3'
services:
  nginx:
    container_name: daily-nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  mysql:
    container_name: daily-mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: daily
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config/my.cnf:/etc/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    restart: always

  hbase:
    container_name: daily-hbase
    image: harisekhon/hbase
    hostname: "daily-hbase"
    ports:
      - "2181:2181"
      - "8080:8080"
      - "8085:8085"
      - "9090:9090"
      - "9095:9095"
      - "16000:16000"
      - "16010:16010"
      - "16201:16201"
      - "16301:16301"
    restart: always

  elasticsearch:
    container_name: daily-es
    image: elasticsearch:6.5.3
    environment:
      discovery.type: "single-node"
    network_mode: host
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always

  elasticsearch-head:
    container_name: daily-es-head
    image: alivv/elasticsearch-head:latest
    ports:
      - "9100:9100"
    restart: always

  app:
    container_name: daily-service
    restart: always
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    expose:
      - "8081"
    depends_on:
      - nginx
      - mysql
      - hbase
      - elasticsearch
      - elasticsearch-head
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker