version: '3'
services:
  nginx:
   container_name: daily-nginx
   image: nginx:latest
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d

  mysql:
   container_name: daily-mysql
   image: mysql:5.7
   environment:
    MYSQL_DATABASE: daily
    MYSQL_ROOT_PASSWORD: admin
    MYSQL_ROOT_HOST: '%'
   volumes:
    - ./mysql/data:/var/lib/mysql
    - ./mysql/config/my.cnf:/etc/my.cnf
    - ./mysql/init:/docker-entrypoint-initdb.d/
   ports:
   - "3306:3306"
   restart: always

  app:
    container_name: daily-service
    restart: always
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    expose:
      - "8081"
    depends_on:
      - nginx
      - mysql
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker