DROP TABLE IF EXISTS t_record;
CREATE TABLE IF NOT EXISTS t_record(
  id INTEGER AUTO_INCREMENT PRIMARY KEY ,
  template_id INTEGER NOT NULL ,
  del TINYINT DEFAULT FALSE ,
  createOn DATETIME DEFAULT CURRENT_TIMESTAMP,
  updateOn DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)DEFAULT CHARSET 'utf8mb4' ENGINE 'InnoDB';

CREATE TABLE IF NOT EXISTS t_record_property(
  id INTEGER AUTO_INCREMENT PRIMARY KEY ,
  record_id INTEGER NOT NULL ,
  value TEXT,
  del TINYINT DEFAULT FALSE ,
  createOn DATETIME DEFAULT CURRENT_TIMESTAMP,
  updateOn DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)DEFAULT CHARSET 'utf8mb4' ENGINE 'InnoDB';
