CREATE TABLE IF NOT EXISTS t_learn_entry
(
  id          INTEGER AUTO_INCREMENT PRIMARY KEY,
  keyword     VARCHAR(255) NOT NULL COMMENT 'keyword',
  pinyin      VARCHAR(255) NOT NULL COMMENT 'pinyin',
  description text COMMENT 'description',
  del         TINYINT  DEFAULT FALSE,
  createOn    DATETIME DEFAULT CURRENT_TIMESTAMP,
  updateOn    DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT CHARSET 'utf8mb4'
  ENGINE 'InnoDB';