CREATE TABLE IF NOT EXISTS t_user(
  id INTEGER AUTO_INCREMENT PRIMARY KEY ,
  name VARCHAR(64) NOT NULL ,
  password VARCHAR(256) NULL ,
  del TINYINT DEFAULT FALSE ,
  createOn DATETIME DEFAULT CURRENT_TIMESTAMP,
  updateOn DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)DEFAULT CHARSET 'utf8mb4' ENGINE 'InnoDB';