CREATE TABLE IF NOT EXISTS t_feature(
  id INTEGER AUTO_INCREMENT PRIMARY KEY ,
  name VARCHAR(64) NOT NULL ,
  description VARCHAR(256) NULL ,
  del TINYINT DEFAULT FALSE ,
  createOn DATETIME DEFAULT CURRENT_TIMESTAMP,
  updateOn DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)DEFAULT CHARSET 'utf8mb4' ENGINE 'InnoDB';

CREATE TABLE IF NOT EXISTS t_module_feature(
  id INTEGER AUTO_INCREMENT PRIMARY KEY ,
  module_id INTEGER NOT NULL ,
  feature_id INTEGER NOT NULL ,
  del TINYINT DEFAULT FALSE ,
  createOn DATETIME DEFAULT CURRENT_TIMESTAMP,
  updateOn DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)DEFAULT CHARSET 'utf8mb4' ENGINE 'InnoDB';
