CREATE TABLE IF NOT EXISTS t_record(
  id INTEGER AUTO_INCREMENT PRIMARY KEY ,
  feature_id INTEGER NOT NULL ,
  owner_id INTEGER COMMENT '持有人',
  name VARCHAR(64) NOT NULL COMMENT '名称',
  type INTEGER DEFAULT 0 COMMENT '类型',
  content VARCHAR(512) COMMENT '内容',
  remarks VARCHAR(256) NULL COMMENT '备注',
  del TINYINT DEFAULT FALSE ,
  createOn DATETIME DEFAULT CURRENT_TIMESTAMP,
  updateOn DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)DEFAULT CHARSET 'utf8mb4' ENGINE 'InnoDB';